<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Key_VSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $answers = [
            ['no' => 1, 'answer' => 'B', 'type' => 'C'],
            ['no' => 2, 'answer' => 'C', 'type' => 'N'],
            ['no' => 3, 'answer' => 'A', 'type' => 'A'],
            ['no' => 4, 'answer' => 'B', 'type' => 'C'],
            ['no' => 5, 'answer' => 'C', 'type' => 'N'],
            ['no' => 6, 'answer' => 'C', 'type' => 'A'],
            ['no' => 7, 'answer' => 'D', 'type' => 'C'],
            ['no' => 8, 'answer' => 'A', 'type' => 'A'],
            ['no' => 9, 'answer' => 'C', 'type' => 'N'],
            ['no' => 10, 'answer' => 'B', 'type' => 'C'],
            ['no' => 11, 'answer' => 'B', 'type' => 'N'],
            ['no' => 12, 'answer' => 'E', 'type' => 'A'],
            ['no' => 13, 'answer' => 'C', 'type' => 'N'],
            ['no' => 14, 'answer' => 'E', 'type' => 'C'],
            ['no' => 15, 'answer' => 'B', 'type' => 'A'],
            ['no' => 16, 'answer' => 'A', 'type' => 'N'],
            ['no' => 17, 'answer' => 'D', 'type' => 'C'],
            ['no' => 18, 'answer' => 'D', 'type' => 'A'],
            ['no' => 19, 'answer' => 'C', 'type' => 'N'],
            ['no' => 20, 'answer' => 'D', 'type' => 'C'],
            ['no' => 21, 'answer' => 'B', 'type' => 'A'],
            ['no' => 22, 'answer' => 'B', 'type' => 'N'],
            ['no' => 23, 'answer' => 'C', 'type' => 'C'],
            ['no' => 24, 'answer' => 'B', 'type' => 'A'],
            ['no' => 25, 'answer' => 'D', 'type' => 'C'],
            ['no' => 26, 'answer' => 'B', 'type' => 'N'],
            ['no' => 27, 'answer' => 'B', 'type' => 'A'],
            ['no' => 28, 'answer' => 'A', 'type' => 'N'],
            ['no' => 29, 'answer' => 'E', 'type' => 'A'],
            ['no' => 30, 'answer' => 'B', 'type' => 'C'],
            ['no' => 31, 'answer' => 'C', 'type' => 'A'],
            ['no' => 32, 'answer' => 'B', 'type' => 'C'],
            ['no' => 33, 'answer' => 'E', 'type' => 'N'],
            ['no' => 34, 'answer' => 'E', 'type' => 'A'],
            ['no' => 35, 'answer' => 'D', 'type' => 'N'],
            ['no' => 36, 'answer' => 'D', 'type' => 'A'],
            ['no' => 37, 'answer' => 'B', 'type' => 'C'],
            ['no' => 38, 'answer' => 'C', 'type' => 'A'],
            ['no' => 39, 'answer' => 'C', 'type' => 'A'],
            ['no' => 40, 'answer' => 'A', 'type' => 'C'],
            ['no' => 41, 'answer' => 'B', 'type' => 'N'],
            ['no' => 42, 'answer' => 'C', 'type' => 'A'],
            ['no' => 43, 'answer' => 'D', 'type' => 'C'],
            ['no' => 44, 'answer' => 'D', 'type' => 'C'],
            ['no' => 45, 'answer' => 'D', 'type' => 'N'],
            ['no' => 46, 'answer' => 'E', 'type' => 'C'],
            ['no' => 47, 'answer' => 'E', 'type' => 'A'],
            ['no' => 48, 'answer' => 'A', 'type' => 'C'],
            ['no' => 49, 'answer' => 'E', 'type' => 'C'],
            ['no' => 50, 'answer' => 'D', 'type' => 'A'],
            ['no' => 51, 'answer' => 'C', 'type' => 'N'],
            ['no' => 52, 'answer' => 'D', 'type' => 'N'],
            ['no' => 53, 'answer' => 'A', 'type' => 'A'],
            ['no' => 54, 'answer' => 'B', 'type' => 'A'],
            ['no' => 55, 'answer' => 'A', 'type' => 'A'],
            ['no' => 56, 'answer' => 'E', 'type' => 'C'],
            ['no' => 57, 'answer' => 'A', 'type' => 'N'],
            ['no' => 58, 'answer' => 'D', 'type' => 'A'],
            ['no' => 59, 'answer' => 'E', 'type' => 'C'],
            ['no' => 60, 'answer' => 'A', 'type' => 'N'],
            ['no' => 61, 'answer' => 'D', 'type' => 'C'],
            ['no' => 62, 'answer' => 'C', 'type' => 'N'],
            ['no' => 63, 'answer' => 'D', 'type' => 'C'],
            ['no' => 64, 'answer' => 'C', 'type' => 'A'],
            ['no' => 65, 'answer' => 'E', 'type' => 'N'],
            ['no' => 66, 'answer' => 'B', 'type' => 'A'],
            ['no' => 67, 'answer' => 'E', 'type' => 'N'],
            ['no' => 68, 'answer' => 'E', 'type' => 'C'],
            ['no' => 69, 'answer' => 'C', 'type' => 'A'],
            ['no' => 70, 'answer' => 'D', 'type' => 'N'],
            ['no' => 71, 'answer' => 'E', 'type' => 'N'],
            ['no' => 72, 'answer' => 'B', 'type' => 'A'],
            ['no' => 73, 'answer' => 'A', 'type' => 'C'],
            ['no' => 74, 'answer' => 'A', 'type' => 'C'],
            ['no' => 75, 'answer' => 'E', 'type' => 'N'],
            ['no' => 76, 'answer' => 'B', 'type' => 'C'],
            ['no' => 77, 'answer' => 'B', 'type' => 'A'],
            ['no' => 78, 'answer' => 'A', 'type' => 'N'],
            ['no' => 79, 'answer' => 'C', 'type' => 'C'],
            ['no' => 80, 'answer' => 'E', 'type' => 'C'],
            ['no' => 81, 'answer' => 'A', 'type' => 'N'],
            ['no' => 82, 'answer' => 'C', 'type' => 'C'],
            ['no' => 83, 'answer' => 'A', 'type' => 'A'],
            ['no' => 84, 'answer' => 'C', 'type' => 'N'],
            ['no' => 85, 'answer' => 'A', 'type' => 'A'],
            ['no' => 86, 'answer' => 'E', 'type' => 'N'],
            ['no' => 87, 'answer' => 'D', 'type' => 'A'],
            ['no' => 88, 'answer' => 'C', 'type' => 'N'],
            ['no' => 89, 'answer' => 'E', 'type' => 'A'],
            ['no' => 90, 'answer' => 'B', 'type' => 'N'],
            ['no' => 91, 'answer' => 'E', 'type' => 'A'],
            ['no' => 92, 'answer' => 'C', 'type' => 'C'],
            ['no' => 93, 'answer' => 'E', 'type' => 'A'],
            ['no' => 94, 'answer' => 'B', 'type' => 'A'],
            ['no' => 95, 'answer' => 'E', 'type' => 'N'],
            ['no' => 96, 'answer' => 'B', 'type' => 'C'],
            ['no' => 97, 'answer' => 'B', 'type' => 'C'],
            ['no' => 98, 'answer' => 'D', 'type' => 'N'],
            ['no' => 99, 'answer' => 'B', 'type' => 'C'],
            ['no' => 100, 'answer' => 'B', 'type' => 'N'],
        ];
        DB::table('Key_V')->insert($answers);
    }
}
